# A simple script to parse JSON objects and display relevant data.
# Error-handling is performed for invalid profiles.
# Authors: Adikar Bharath NVS, Ayush Gupta, Prathmesh Dahikar, Sai Siddarth V
# Last Updated: 9/11/2018

#===============================================================================

# Importing the json library included with Python3 for use in the program.

import json

#===============================================================================

def main(): 

	# Create local JSON objects for use in the program.
	# Files are generated by main_script.sh.

	with open('codeforces_user.json') as f_user:
	    data_user = json.load(f_user)

	with open('codeforces_ac.json') as f_ac:
	    data_ac = json.load(f_ac)

	# If the profile is invalid, terminate the script.

	if data_user["status"] == "FAILED" or data_ac["status"] == "FAILED":
		print("No CodeForces profile associated with this handle.")
		exit(1)

	# Access different values of the data_user JSON object.

	print("Current rating:",data_user["result"][0]["rating"])
	print("Current rank:",data_user["result"][0]["rank"])

	# Count number of instances of a particular value in the data_ac JSON object.

	ac_problems = 0
	for i in range(0,len(data_ac["result"])):
		if data_ac["result"][i]["verdict"] == 'OK':
			ac_problems = ac_problems + 1

	print("Accepted Solutions: " + str(ac_problems))

#===============================================================================

# Calling the main() function.
	
if __name__ == '__main__':
	main()

#===============================================================================